### ISSUE TITLE
why remove that this script is forked?

### ISSUE THREAD

**Issue by BoBBer446** [hathagat/debian-installer#1]
Es freut uns ja, dass du Interesse hast das script weiter zu entwickeln und es für Debian zu optimieren scheinst aber wieso der Mehraufwand damit der forked tag weg ist? 

Ich frage deshalb, weil es ja sein kann das Du dafür spezielle Gründe zwecks Lizenz hast.

Einige Änderungen scheinen auch durchaus Sinn zu machen. Der ursprüngliche Gedanke bei OpenSource und Github ist ja auch der, das man zusammen arbeitet und arbeiten kann.

Viel Glück wünschen wir Dir natürlich dennoch bei deinem vorhaben.

**Comment by hathagat** [comment]
Ich wollte keineswegs den Ursprung des Skripts verschleiern. Daher auch in der Readme:
> Thanks to [shoujii](https://github.com/shoujii), [BoBBer446](https://github.com/BoBBer446) and [Zypr](https://github.com/zypr) for the awesome [initial script](https://github.com/shoujii/NeXt-Server)!

Ich möchte aus dem momentanen Skript lediglich Komponenten zur Basisinstallation nutzen und sämtliche installierbare Anwendungen durch Container ersetzen. D.h. von den ursprünglichen Dateien werde ich das meiste löschen und vom ursprünglichen Skript bleibt nicht viel über.

Ich habe den Fork entfernt, da ich versucht habe einen zweiten Fork zu erstellen und das GitHub nicht zulässt. Den zweiten wollte ich erstellen, da ich einige kleinere Bugs im ursprünglichen Skript gefunden hatte und die per Issue bzw. Pull-Request an euch senden wollte (sobald meins wenigstens lauffähig ist).

Falls es da einen besseren Weg gibt, bin ich für jeden Tip dankbar...! :wink:
Dann könnte ich den forked Tag auch problemlos wieder herstellen.

**Comment by BoBBer446** [comment]
Nene alles gut. Konnte Dich nur irgendwie nicht anders erreichen. Ich bin nicht der, der auf GitHub viel unterwegs ist und mir war es nur aufgefallen. Kannst den  Issue gern löschen.  Finde es doof, das es hier keine PMs gibt oder habe ich das übersehen?

**Comment by hathagat** [comment]
Ne, PMs gibt es nicht. Ich bin auch nicht so der Git Profi, daher war ich mir unsicher, ob es nicht doch nen anderen Weg gibt.

Da muss ich mir wohl doch mal Telegram runterladen... :smirk:
